name: planner
description: "A Flutter calendar planner with CRUD and soft delete."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  syncfusion_flutter_calendar: ^30.1.39
  dropdown_button2: ^2.3.9
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true